### ISSUE TITLE
README 提到割闌尾的資訊的考古

### ISSUE THREAD

**Issue by yurenju** [tueeit/TaiwanPlebiscitePetitionSheetGenerator#31]
在 README 裡面提到

> 割闌尾計畫曾經建立線上連署器，這是我們所知的第一份實作，雖然形式仍是實體連署，但利用資訊技術降低了部份實體連署的問題，簡化了連署流程並確保了一致連署資料格式，其發想及方便性令我們印象深刻。
> 但割闌尾計畫的相關工具並沒有釋出，也隨著計畫結束而消失。

前端的部分我參與了很多，所有前端都是開放源碼的，源碼在下面網址：

https://github.com/appy-tw/appytw.github.io/tree/master/print

production 的 PDF 產生的部分是因為在後端實作，那邊我確實沒有源碼。但是前端那個時候也是有試著實作一份純前端的 PDF 產生器，我沒記錯的話應該是沒寫完，但是應該套版是可以的了。

https://github.com/appy-tw/appytw.github.io/tree/master/test

另外我們還實作了可以直接傳送到 7-11 iBon 的機制，同樣為 MIT，歡迎將原本的功能移植過來。

https://github.com/appy-tw/appytw.github.io/blob/master/print/js/main.js#L137-L155

**Comment by chuck-lee** [comment]
後端好像在這裡？ https://github.com/appy-tw/Appendectomy

**Comment by yurenju** [comment]
@chuck-lee  看起來是，不過還要進去翻找一下才知道在哪。這樣的話 README 可以修改一下 XD  看到 commit 了！！
