### ISSUE TITLE
建議強制使用 https

### ISSUE THREAD

**Issue by danny50610** [tueeit/TaiwanPlebiscitePetitionSheetGenerator#33]
如果直接前往 https://tueeit.github.io/TaiwanPlebiscitePetitionSheetGenerator/
會跳到 http://petition.tueeit.org.tw/
不過 https://petition.tueeit.org.tw/ 看起來是能用的

雖然PDF是在瀏覽器產生的，不過https能用就盡量用吧

關於設定的部分，有找到一篇文章：
https://help.github.com/articles/securing-your-github-pages-site-with-https/

可以參考看看

**Comment by chuck-lee** [comment]
感謝提醒，之前就有開HTTPS但是github page的自動簽章一直沒有生出來，放著放著就忘了，然後放著放著就好了 XD

已經改為強制HTTPS～
